title: "timer-doctor"
description: "Audit your systemd timers"
theme: jekyll-theme-cayman
url: "https://HeytalePazguato.github.io"
baseurl: "/timer-doctor"

show_downloads: true
github:
  repository_url: "https://github.com/HeytalePazguato/timer-doctor"

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true

include:
  - CHANGELOG.md
